<?php

namespace Database\Seeders;

use App\Models\Produk;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Makanan Ringan (kategori 1)
            [
                'id_produk' => '8992761201018',
                'nama' => 'Chitato BBQ 68g',
                'gambar' => null,
                'nomor_bpom' => 'MD224510107077',
                'harga' => 8500.00,
                'biaya_produk' => 6800.00,
                'stok' => 50,
                'batas_stok' => 10,
                'satuan' => 'pcs',
                'satuan_pack' => 'karton',
                'isi_per_pack' => 24,
                'harga_pack' => 192000.00,
                'min_beli_diskon' => 12,
                'harga_diskon_unit' => 8000.00,
                'harga_diskon_pack' => 180000.00,
                'id_kategori' => 1,
            ],
            [
                'id_produk' => '8992761201025',
                'nama' => 'Taro Rumput Laut 57g',
                'gambar' => null,
                'nomor_bpom' => 'MD224510107078',
                'harga' => 7500.00,
                'biaya_produk' => 6000.00,
                'stok' => 45,
                'batas_stok' => 10,
                'satuan' => 'pcs',
                'satuan_pack' => 'karton',
                'isi_per_pack' => 24,
                'harga_pack' => 168000.00,
                'min_beli_diskon' => 12,
                'harga_diskon_unit' => 7000.00,
                'harga_diskon_pack' => 156000.00,
                'id_kategori' => 1,
            ],
            // Minuman (kategori 2)
            [
                'id_produk' => '8996001600016',
                'nama' => 'Coca Cola 330ml',
                'gambar' => null,
                'nomor_bpom' => 'MD805003010033',
                'harga' => 5000.00,
                'biaya_produk' => 4000.00,
                'stok' => 100,
                'batas_stok' => 20,
                'satuan' => 'pcs',
                'satuan_pack' => 'karton',
                'isi_per_pack' => 24,
                'harga_pack' => 110000.00,
                'min_beli_diskon' => 12,
                'harga_diskon_unit' => 4500.00,
                'harga_diskon_pack' => 100000.00,
                'id_kategori' => 2,
            ],
            [
                'id_produk' => '8996001600023',
                'nama' => 'Sprite 330ml',
                'gambar' => null,
                'nomor_bpom' => 'MD805003010034',
                'harga' => 5000.00,
                'biaya_produk' => 4000.00,
                'stok' => 80,
                'batas_stok' => 20,
                'satuan' => 'pcs',
                'satuan_pack' => 'karton',
                'isi_per_pack' => 24,
                'harga_pack' => 110000.00,
                'min_beli_diskon' => 12,
                'harga_diskon_unit' => 4500.00,
                'harga_diskon_pack' => 100000.00,
                'id_kategori' => 2,
            ],
            // Produk Susu (kategori 3)
            [
                'id_produk' => '8992761300013',
                'nama' => 'Ultra Milk Coklat 200ml',
                'gambar' => null,
                'nomor_bpom' => 'MD805003010035',
                'harga' => 6000.00,
                'biaya_produk' => 4800.00,
                'stok' => 60,
                'batas_stok' => 15,
                'satuan' => 'pcs',
                'satuan_pack' => 'karton',
                'isi_per_pack' => 24,
                'harga_pack' => 132000.00,
                'min_beli_diskon' => 12,
                'harga_diskon_unit' => 5500.00,
                'harga_diskon_pack' => 120000.00,
                'id_kategori' => 3,
            ],
            // Roti & Kue (kategori 4)
            [
                'id_produk' => '8992761400014',
                'nama' => 'Roti Tawar Sari Roti 400g',
                'gambar' => null,
                'nomor_bpom' => 'MD805003010036',
                'harga' => 12000.00,
                'biaya_produk' => 9600.00,
                'stok' => 30,
                'batas_stok' => 5,
                'satuan' => 'pcs',
                'satuan_pack' => 'karton',
                'isi_per_pack' => 12,
                'harga_pack' => 132000.00,
                'min_beli_diskon' => 6,
                'harga_diskon_unit' => 11000.00,
                'harga_diskon_pack' => 120000.00,
                'id_kategori' => 4,
            ],
            // Bumbu & Rempah (kategori 5)
            [
                'id_produk' => '8992761500015',
                'nama' => 'Royco Rasa Ayam 80g',
                'gambar' => null,
                'nomor_bpom' => 'MD805003010037',
                'harga' => 8000.00,
                'biaya_produk' => 6400.00,
                'stok' => 40,
                'batas_stok' => 8,
                'satuan' => 'pcs',
                'satuan_pack' => 'karton',
                'isi_per_pack' => 24,
                'harga_pack' => 176000.00,
                'min_beli_diskon' => 12,
                'harga_diskon_unit' => 7500.00,
                'harga_diskon_pack' => 168000.00,
                'id_kategori' => 5,
            ],
            // Mie Instan (kategori 6)
            [
                'id_produk' => '8992761600016',
                'nama' => 'Indomie Goreng 85g',
                'gambar' => null,
                'nomor_bpom' => 'MD805003010038',
                'harga' => 3000.00,
                'biaya_produk' => 2400.00,
                'stok' => 200,
                'batas_stok' => 50,
                'satuan' => 'pcs',
                'satuan_pack' => 'karton',
                'isi_per_pack' => 40,
                'harga_pack' => 110000.00,
                'min_beli_diskon' => 20,
                'harga_diskon_unit' => 2800.00,
                'harga_diskon_pack' => 100000.00,
                'id_kategori' => 6,
            ],
            // Beras & Tepung (kategori 7)
            [
                'id_produk' => '8992761700017',
                'nama' => 'Beras Ramos 5kg',
                'gambar' => null,
                'nomor_bpom' => 'MD805003010039',
                'harga' => 75000.00,
                'biaya_produk' => 60000.00,
                'stok' => 20,
                'batas_stok' => 3,
                'satuan' => 'karung',
                'satuan_pack' => 'pallet',
                'isi_per_pack' => 10,
                'harga_pack' => 700000.00,
                'min_beli_diskon' => 5,
                'harga_diskon_unit' => 70000.00,
                'harga_diskon_pack' => 650000.00,
                'id_kategori' => 7,
            ],
            // Produk Kesehatan (kategori 8)
            [
                'id_produk' => '8992761800018',
                'nama' => 'Tolak Angin 15ml',
                'gambar' => null,
                'nomor_bpom' => 'TR805003010040',
                'harga' => 3500.00,
                'biaya_produk' => 2800.00,
                'stok' => 80,
                'batas_stok' => 15,
                'satuan' => 'sachet',
                'satuan_pack' => 'box',
                'isi_per_pack' => 12,
                'harga_pack' => 38000.00,
                'min_beli_diskon' => 6,
                'harga_diskon_unit' => 3200.00,
                'harga_diskon_pack' => 36000.00,
                'id_kategori' => 8,
            ],
        ];

        foreach ($products as $product) {
            Produk::create($product);
        }
    }
}
